### ISSUE TITLE
Compiling error for LAMMPS 7 Aug 2019

### ISSUE THREAD

**Issue by Dezhao-Huang** [groupdepablo/USER-3SPN2#2]
To reproduce the error:
first, I have downloaded latest lammps version 7 Aug 2019 and the USER-2SPN2 folder.
I copied the USER-2SPN2 folder into the src folder of LAMMPS.
In src folder:
module load ompi
make icc_openmpi -j 12
make yes-CLASS2
make yes-MOLECULE
make yes-USER-2SPN2
make icc_openmpi -j 12
Then the error shows:

Gathering installed package information (may take a little while)
make[1]: Entering directory `/scratch365/dhuang2/si_DNA/mylammps/src'
Gathering git version information
make[1]: Leaving directory `/scratch365/dhuang2/si_DNA/mylammps/src'
Compiling LAMMPS for machine icc_openmpi
make[1]: Entering directory `/scratch365/dhuang2/si_DNA/mylammps/src/Obj_icc_openmpi'
make[1]: Leaving directory `/scratch365/dhuang2/si_DNA/mylammps/src/Obj_icc_openmpi'
make[1]: Entering directory `/scratch365/dhuang2/si_DNA/mylammps/src/Obj_icc_openmpi'
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../pair_lj_charmm_coul_charmm.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../atom.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../pair_lj_class2.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../angle_list.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../dihedral_3spn2.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../pair_lj_charmm_coul_charmm_implicit.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../pair_lj_class2_coul_long.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../improper_umbrella.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../bond_nonlinear.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../bond_quartic.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../atom_vec_bond.cpp
mpicxx -g -O3 -restrict  -DLAMMPS_GZIP  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1    -c ../bond_list.cpp
../angle_list.cpp(254): error: argument of type "int" is incompatible with parameter of type "char *"
    force->bounds(arg[0],atom->nangletypes,ilo,ihi);
                                           ^

../angle_list.cpp(254): error #165: too few arguments in function call
    force->bounds(arg[0],atom->nangletypes,ilo,ihi);
                                                  ^

compilation aborted for ../angle_list.cpp (code 2)
make[1]: *** [angle_list.o] Error 2
make[1]: *** Waiting for unfinished jobs....
../bond_list.cpp(221): error: argument of type "int" is incompatible with parameter of type "char *"
    force->bounds(arg[0],atom->nbondtypes,ilo,ihi);
                                          ^

../bond_list.cpp(221): error #165: too few arguments in function call
    force->bounds(arg[0],atom->nbondtypes,ilo,ihi);
                                                 ^

compilation aborted for ../bond_list.cpp (code 2)
make[1]: *** [bond_list.o] Error 2
../dihedral_3spn2.cpp(299): error: argument of type "int" is incompatible with parameter of type "char *"
    force->bounds(arg[0],atom->ndihedraltypes,ilo,ihi);
                                              ^

../dihedral_3spn2.cpp(299): error #165: too few arguments in function call
    force->bounds(arg[0],atom->ndihedraltypes,ilo,ihi);
                                                     ^

compilation aborted for ../dihedral_3spn2.cpp (code 2)
make[1]: *** [dihedral_3spn2.o] Error 2
make[1]: Leaving directory `/scratch365/dhuang2/si_DNA/mylammps/src/Obj_icc_openmpi'
make: *** [icc_openmpi] Error 2

**Comment by lequieu** [comment]
USER-3SPN is currently only compatible up to the 13 Jan 2014 version of LAMMPS. Try that version of LAMMPS and see if you can get the code to compile.

**Comment by lequieu** [comment]
Addressed in Pull Request #3
